# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vec_to_symmat <- function(x) {
    .Call(`_spamtree_vec_to_symmat`, x)
}

CrossCovarianceAG10 <- function(coords1, mv1, coords2, mv2, ai1, ai2, phi_i, thetamv, Dmat) {
    .Call(`_spamtree_CrossCovarianceAG10`, coords1, mv1, coords2, mv2, ai1, ai2, phi_i, thetamv, Dmat)
}

find_not_nan <- function(infield, filtering) {
    .Call(`_spamtree_find_not_nan`, infield, filtering)
}

list_mean <- function(x) {
    .Call(`_spamtree_list_mean`, x)
}

list_cubes_mean <- function(x, cslice) {
    .Call(`_spamtree_list_cubes_mean`, x, cslice)
}

list_qtile <- function(x, q) {
    .Call(`_spamtree_list_qtile`, x, q)
}

par_huvtransf_fwd <- function(par, set_unif_bounds) {
    .Call(`_spamtree_par_huvtransf_fwd`, par, set_unif_bounds)
}

par_huvtransf_back <- function(par, set_unif_bounds) {
    .Call(`_spamtree_par_huvtransf_back`, par, set_unif_bounds)
}

spamtree_mv_mcmc <- function(y, X, Z, coords, mv_id, blocking, gix_block, res_is_ref, parents, children, limited_tree, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, start_w, theta, beta, tausq, mcmcsd, mcmc_keep = 100L, mcmc_burn = 100L, mcmc_thin = 1L, num_threads = 1L, use_alg = 'S', adapting = FALSE, main_verbose = TRUE, verbose = FALSE, debug = FALSE, printall = FALSE, sample_beta = TRUE, sample_tausq = TRUE, sample_theta = TRUE, sample_w = TRUE, sample_predicts = TRUE) {
    .Call(`_spamtree_spamtree_mv_mcmc`, y, X, Z, coords, mv_id, blocking, gix_block, res_is_ref, parents, children, limited_tree, layer_names, layer_gibbs_group, indexing, set_unif_bounds_in, start_w, theta, beta, tausq, mcmcsd, mcmc_keep, mcmc_burn, mcmc_thin, num_threads, use_alg, adapting, main_verbose, verbose, debug, printall, sample_beta, sample_tausq, sample_theta, sample_w, sample_predicts)
}

kthresholds <- function(x, k) {
    .Call(`_spamtree_kthresholds`, x, k)
}

col_to_string <- function(X) {
    .Call(`_spamtree_col_to_string`, X)
}

part_axis_parallel_lmt <- function(coords, thresholds) {
    .Call(`_spamtree_part_axis_parallel_lmt`, coords, thresholds)
}

make_edges <- function(parchimat, non_empty_blocks, res_is_ref) {
    .Call(`_spamtree_make_edges`, parchimat, non_empty_blocks, res_is_ref)
}

make_edges_limited <- function(parchimat, non_empty_blocks, res_is_ref) {
    .Call(`_spamtree_make_edges_limited`, parchimat, non_empty_blocks, res_is_ref)
}

number_revalue <- function(original_mat, from_val, to_val) {
    .Call(`_spamtree_number_revalue`, original_mat, from_val, to_val)
}

